config/routes.rb
Rails.application.routes.draw do
  
  root 'programs#index'
  resources :programs do
    collection { post :import }
  end   
  resources :adjustments
  
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
	require 'roo'
	def self.import(path)
    xlsx = Roo::Spreadsheet.open(path)
    xlsx.each_with_index do |row, index|
    	if index != 0
    		# adjustment = Adjustment.new(ltv:)
      # 	adjustment.save
      end	
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord
  
 require 'csv'
 require 'roo-xls'
  
  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file, extension: :xls)
    sheet = spreadsheet.sheet("Conforming Fixed Rate")

    @program = Program.new()
    @program.loan_purpose = "Purchase"
    @program.loan_size = sheet.row(5)[0]
    @program.loan_type = sheet.row(7)[1]

    term1 = sheet.row(8)[2]
    term2 = sheet.row(8)[3]
    term3 = sheet.row(8)[4]
    term4 = sheet.row(8)[5]

    ltv1 = sheet.row(122)[8]
    ltv2 = sheet.row(122)[9]
    ltv3 = sheet.row(122)[10]
    ltv4 = sheet.row(122)[11]
    ltv5 = sheet.row(122)[13]
    ltv6 = sheet.row(122)[14]
    ltv7 = sheet.row(122)[15]
    ltv8 = sheet.row(122)[16]
    ltv9 = sheet.row(122)[17]

    base_rate_hash = Hash.new
    adjustment_rate_hash = Hash.new

    sheet.each_with_index do |row, index|
      if index >= 8 && index <= 33
        base_rate_hash[row[1]] = {"#{term1}": row[2].round(3), "#{term2}": row[3].round(3), "#{term3}": row[4].round(3), "#{term4}": row[5].round(3)}
      end

      if index >= 122 && index <= 129
        adjustment_rate_hash[row[5]] = {"#{ltv1}": row[8], "#{ltv2}": row[9], "#{ltv3}": row[10], "#{ltv4}": row[11], "#{ltv5}": row[13], "#{ltv6}": row[14], "#{ltv7}": row[15], "#{ltv8}": row[16], "#{ltv9}": row[17]}
      end

    end
    @program.base_rate = base_rate_hash
    @program.adjustment_rate = adjustment_rate_hash
    @program.save
  end

end

app/controllers/adjustments_controller.rb
class AdjustmentsController < ApplicationController
  before_action :set_adjustment, only: [:show, :edit, :update, :destroy]

  # GET /adjustments
  # GET /adjustments.json
  def index
    @adjustments = Adjustment.all
  end

  # GET /adjustments/1
  # GET /adjustments/1.json
  def show
  end

  # def import
  #   @adjustments = Adjustment.import(params[:file].path)
  #   redirect_to :back
  # end


  # GET /adjustments/new
  def new
    @adjustment = Adjustment.new
  end

  # GET /adjustments/1/edit
  def edit
  end

  # POST /adjustments
  # POST /adjustments.json
  def create
    @adjustment = Adjustment.new(adjustment_params)

    respond_to do |format|
      if @adjustment.save
        format.html { redirect_to @adjustment, notice: 'Adjustment was successfully created.' }
        format.json { render :show, status: :created, location: @adjustment }
      else
        format.html { render :new }
        format.json { render json: @adjustment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adjustments/1
  # PATCH/PUT /adjustments/1.json
  def update
    respond_to do |format|
      if @adjustment.update(adjustment_params)
        format.html { redirect_to @adjustment, notice: 'Adjustment was successfully updated.' }
        format.json { render :show, status: :ok, location: @adjustment }
      else
        format.html { render :edit }
        format.json { render json: @adjustment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adjustments/1
  # DELETE /adjustments/1.json
  def destroy
    @adjustment.destroy
    respond_to do |format|
      format.html { redirect_to adjustments_url, notice: 'Adjustment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adjustment
      @adjustment = Adjustment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adjustment_params
      params.require(:adjustment).permit(:ltv, :fico)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  def import
    @programs = Program.import(params[:file].path)
    redirect_to root_url, notice: "Program imported."
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:loan_purpose, :loan_size, :loan_type, :term, :interest_rate, :lock_period, :fannie_mae, :base_rate, :adjustment_rate)
    end
end

app/helpers/adjustments_helper.rb
module AdjustmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/adjustments/_form.html.erb
<%= form_with(model: adjustment, local: true) do |form| %>
  <% if adjustment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adjustment.errors.count, "error") %> prohibited this adjustment from being saved:</h2>

      <ul>
      <% adjustment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ltv %>
    <%= form.number_field :ltv %>
  </div>

  <div class="field">
    <%= form.label :fico %>
    <%= form.number_field :fico %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adjustments/edit.html.erb
<h1>Editing Adjustment</h1>

<%= render 'form', adjustment: @adjustment %>

<%= link_to 'Show', @adjustment %> |
<%= link_to 'Back', adjustments_path %>

app/views/adjustments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adjustments</h1>

<table>
  <thead>
    <tr>
      <th>Ltv</th>
      <th>Fico</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adjustments.each do |adjustment| %>
      <tr>
        <td><%= adjustment.ltv %></td>
        <td><%= adjustment.fico %></td>
        <td><%= link_to 'Show', adjustment %></td>
        <td><%= link_to 'Edit', edit_adjustment_path(adjustment) %></td>
        <td><%= link_to 'Destroy', adjustment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adjustment', new_adjustment_path %>

app/views/adjustments/new.html.erb
<h1>New Adjustment</h1>

<%= render 'form', adjustment: @adjustment %>

<%= link_to 'Back', adjustments_path %>

app/views/adjustments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ltv:</strong>
  <%= @adjustment.ltv %>
</p>

<p>
  <strong>Fico:</strong>
  <%= @adjustment.fico %>
</p>

<%= link_to 'Edit', edit_adjustment_path(@adjustment) %> |
<%= link_to 'Back', adjustments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateSheet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programs/_form.html.erb
<%= form_with(model: program, local: true) do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :loan_purpose %>
    <%= form.text_field :loan_purpose %>
  </div>

  <div class="field">
    <%= form.label :loan_size %>
    <%= form.text_field :loan_size %>
  </div>

  <div class="field">
    <%= form.label :loan_type %>
    <%= form.text_field :loan_type %>
  </div>

  <div class="field">
    <%= form.label :term %>
    <%= form.number_field :term %>
  </div>

  <div class="field">
    <%= form.label :interest_rate %>
    <%= form.text_field :interest_rate %>
  </div>

  <div class="field">
    <%= form.label :lock_period %>
    <%= form.number_field :lock_period %>
  </div>

  <div class="field">
    <%= form.label :fannie_mae %>
    <%= form.check_box :fannie_mae %>
  </div>

  <div class="field">
    <%= form.label :base_rate %>
    <%= form.text_field :base_rate %>
  </div>

  <div class="field">
    <%= form.label :adjustment_rate %>
    <%= form.text_field :adjustment_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Programs</h1>
<table border="1px">
  <thead>
    <tr>
      <th>Loan purpose</th>
      <th>Loan size</th>
      <th>Loan type</th>
      <th>Term</th>
      <th>Interest rate</th>
      <th>Lock period</th>
      <th>Fannie mae</th>
      <th>Base rate</th>
      <th>Adjustment rate</th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.loan_purpose %></td>
        <td><%= program.loan_size %></td>
        <td><%= program.loan_type %></td>
        <td><%= program.term %></td>
        <td><%= program.interest_rate %></td>
        <td><%= program.lock_period %></td>
        <td><%= program.fannie_mae %></td>
        <td><%= program.base_rate %></td>
        <td><%= program.adjustment_rate %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div align="center">
  <%= form_tag(import_programs_path, :multipart => true) do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</div>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan purpose:</strong>
  <%= @program.loan_purpose %>
</p>

<p>
  <strong>Loan size:</strong>
  <%= @program.loan_size %>
</p>

<p>
  <strong>Loan type:</strong>
  <%= @program.loan_type %>
</p>

<p>
  <strong>Term:</strong>
  <%= @program.term %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @program.interest_rate %>
</p>

<p>
  <strong>Lock period:</strong>
  <%= @program.lock_period %>
</p>

<p>
  <strong>Fannie mae:</strong>
  <%= @program.fannie_mae %>
</p>

<p>
  <strong>Base rate:</strong>
  <%= @program.base_rate %>
</p>

<p>
  <strong>Adjustment rate:</strong>
  <%= @program.adjustment_rate %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>